language: android
android:
  components:
  - tools
  - platform-tools
  - extra
  - android-23
  - build-tools-23.0.2
script:
- gradle clean build
notifications:
  email:
    recipients:
    - jak@microsoft.com
    on_success: never
    on_failure: always
